export { authService } from "./auth";
export type { AuthUser, AuthResponse, LoginInput, SignupInput, SupabaseUser, SupabaseSession } from "./auth";
export { profileService } from "./profile";
export type { UserProfile, UpdateProfileInput } from "./profile";
export { notesService } from "./notes";
export type { Note, Subject, Folder, NoteInput, NoteFilters } from "./notes";
export { flashcardsService } from "./flashcards";
export type { Flashcard, FlashcardInput } from "./flashcards";
export { quizzesService } from "./quizzes";
export type { Quiz, QuizQuestion, QuizAttempt, QuizAttemptResult, LeaderboardEntry } from "./quizzes";
export { plannerService } from "./planner";
export type { PlannerTask, PlannerEvent, PlannerTaskInput, PlannerStatus, PlannerPriority, PlannerRecurrence } from "./planner";
export { dashboardService } from "./dashboard";
export type { DashboardStats } from "./dashboard";
export { notificationsService } from "./notifications";
export type { Notification } from "./notifications";
export { chatService } from "./chat";
export type { ChatSession, ChatConversation, ChatMessage } from "./chat";
export { uploadsService } from "./uploads";
export type { UploadedFile } from "./uploads";
export { aiService } from "./ai";
export { searchService } from "./search";
export type { GlobalSearchResults } from "./search";